name: Build DKVM Image

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
      - '*-dev'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wget \
          expect \
          xorriso \
          qemu-system-x86 \
          ovmf \
          qemu-utils \
          genisoimage

    - name: Run setup script
      env:
        VERSION: ${{ github.ref_name }}
      run: |
        chmod +x setup.sh
        sudo ./setup.sh
        zip -r dkvm-${{ github.ref_name }}.zip dkvm-${{ github.ref_name }}.img README.md


    - name: Create GitHub Release
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dkvm-*.zip
          README.md
        generate_release_notes: true
        draft: false
        prerelease: ${{ contains(github.ref_name, '-dev') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
