name: Build DKVM Image

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
      - '*-dev'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget expect xorriso qemu-system-x86 ovmf qemu-utils genisoimage ovmf

    - name: Run setup script
      env:
        VERSION: ${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}
      run: |
        # Ensure we have a clean environment
        chmod +x setup.sh
        sudo ./setup.sh

    - name: Upload DKVM Image
      uses: actions/upload-artifact@v4
      with:
        name: dkvm-image
        path: dkvm-*.img
        if-no-files-found: error
        retention-days: 5
